# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIqA0GoCKlomeRg9kOmy_wkKR1Q0uBua
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(filename)
df.head()

df['Total'] = df['Quantidade'] * df['Preco_Produto']
print(df)

total_geral = df['Total'].sum()
print(f'O valor total de vendas = {total_geral}')

media = df['Total'].mean()
print(f'A media de vendas = {media}')

df[df['Preco_Produto'] > 99]

df.to_csv('vendas_atualizado.csv')
files.download('vendas_atualizado.csv')